# coding: utf-8

from __future__ import annotations

from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional, Union, Literal  # noqa: F401

from pydantic import ConfigDict, AnyUrl, BaseModel, EmailStr, validator, Field, Extra  # noqa: F401
from aries_cloudcontroller.model.protocol_descriptor import ProtocolDescriptor


class Disclose(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Disclose - a model defined in OpenAPI
        protocols: List of protocol descriptors.
        id: Message identifier [Optional].
        type: Message type [Optional].
    """

    protocols: List[ProtocolDescriptor]
    id: Optional[str] = Field(None, alias="@id")
    type: Optional[str] = Field(None, alias="@type")
    model_config = ConfigDict(populate_by_name=True)


Disclose.update_forward_refs()
