# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Literal, Optional, Union  # noqa: F401

from pydantic import (  # noqa: F401
    AnyUrl,
    BaseModel,
    ConfigDict,
    EmailStr,
    Extra,
    Field,
    field_validator,
)


class IndyProofRequestedProofRevealedAttr(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    IndyProofRequestedProofRevealedAttr - a model defined in OpenAPI
        encoded: Encoded value [Optional].
        raw: Raw value [Optional].
        sub_proof_index: Sub-proof index [Optional].
    """

    encoded: Optional[str] = None
    raw: Optional[str] = None
    sub_proof_index: Optional[int] = None

    @field_validator("encoded")
    @classmethod
    def encoded_pattern(cls, value):
        # Property is optional
        if value is None:
            return

        pattern = r"^-?[0-9]*$"
        if not re.match(pattern, value):
            raise ValueError(
                f"Value of encoded does not match regex pattern ('{pattern}')"
            )
        return value

    model_config = ConfigDict(populate_by_name=True)


IndyProofRequestedProofRevealedAttr.model_rebuild()
